/**
 * storeProof_batch.js
 * 
 * Paper: Privacy-Preserving Verifiable AI Inference in Healthcare
 * Authors: Kezita Jebastine, Jeslyn Liz Jacob
 * 
 * Run with:
 *   npx hardhat run scripts/storeProof_batch.js --network localhost
 * 
 * Or for Sepolia testnet:
 *   npx hardhat run scripts/storeProof_batch.js --network sepolia
 * 
 * Reads commitments from commitments_for_blockchain.json (output of
 * healthcare_zkp.py), calls storeProof() for each one, records gas
 * used and timing — these numbers go in Table 1 of the paper.
 */

const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

// ── Load commitments generated by healthcare_zkp.py ──────────────────────
function loadCommitments() {
  const filePath = path.join(__dirname, "../commitments_for_blockchain.json");
  if (!fs.existsSync(filePath)) {
    // Fallback: use hardcoded test commitments if file not found
    console.log("⚠️  commitments_for_blockchain.json not found.");
    console.log("   Run healthcare_zkp.py first, or using test commitments.\n");
    return [
      { patient_id: "PAT-1000", commitment: "0x" + "a".repeat(64) },
      { patient_id: "PAT-1001", commitment: "0x" + "b".repeat(64) },
      { patient_id: "PAT-1002", commitment: "0x" + "c".repeat(64) },
      { patient_id: "PAT-1003", commitment: "0x" + "d".repeat(64) },
      { patient_id: "PAT-1004", commitment: "0x" + "e".repeat(64) },
    ];
  }
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

async function main() {
  console.log("=".repeat(65));
  console.log("  ZKP Proof Anchoring — Batch Experiment");
  console.log("  Records gas cost + timing for paper evaluation");
  console.log("=".repeat(65));

  // ── Deploy or attach to ProofStorage contract ─────────────────────────
  const ProofStorage = await ethers.getContractFactory("ProofStorage");
  console.log("\n  Deploying ProofStorage contract...");
  const deployStart = Date.now();
  const contract = await ProofStorage.deploy();
  await contract.waitForDeployment();
  const deployTime = Date.now() - deployStart;

  const contractAddress = await contract.getAddress();
  console.log(`  ✅ Contract deployed at: ${contractAddress}`);
  console.log(`  ⏱  Deploy time: ${deployTime} ms\n`);

  // ── Load commitments ──────────────────────────────────────────────────
  const commitments = loadCommitments();
  console.log(`  Processing ${commitments.length} patient commitments...\n`);

  const results = [];

  console.log(
    `${"Run".padEnd(5)} ${"Patient".padEnd(12)} ${"Gas Used".padEnd(12)} ` +
    `${"Time(ms)".padEnd(12)} ${"Verified".padEnd(10)} Commitment`
  );
  console.log("-".repeat(70));

  for (let i = 0; i < commitments.length; i++) {
    const { patient_id, commitment } = commitments[i];

    // Convert commitment string to bytes32
    // Pad or trim to exactly 32 bytes
    const commitHex = commitment.startsWith("0x")
      ? commitment
      : "0x" + commitment;

    // Ensure it's 32 bytes (64 hex chars + 0x prefix)
    const padded = commitHex.slice(0, 66).padEnd(66, "0");
    const bytes32Commitment = padded.slice(0, 66);

    // ── Call storeProof and measure gas + time ────────────────────────
    const t0 = Date.now();
    let gasUsed = 0;
    let txHash = "";

    try {
      const tx = await contract.storeProof(bytes32Commitment);
      const receipt = await tx.wait();
      const elapsed = Date.now() - t0;
      gasUsed = receipt.gasUsed.toString();
      txHash = receipt.hash || receipt.transactionHash;

      // ── Verify the proof was stored ───────────────────────────────
      const verified = await contract.verifyProof(bytes32Commitment);

      console.log(
        `${String(i + 1).padEnd(5)} ${patient_id.padEnd(12)} ` +
        `${gasUsed.padEnd(12)} ${String(elapsed).padEnd(12)} ` +
        `${verified ? "✅ YES" : "❌ NO"} ${bytes32Commitment.slice(0, 18)}...`
      );

      results.push({
        run: i + 1,
        patient_id,
        commitment: bytes32Commitment,
        gas_used: gasUsed,
        tx_time_ms: elapsed,
        verified,
        tx_hash: txHash,
        contract_address: contractAddress,
      });

    } catch (err) {
      console.log(
        `${String(i + 1).padEnd(5)} ${patient_id.padEnd(12)} ERROR: ${err.message.slice(0, 40)}`
      );
      results.push({
        run: i + 1,
        patient_id,
        commitment: bytes32Commitment,
        gas_used: "ERROR",
        tx_time_ms: Date.now() - t0,
        verified: false,
        tx_hash: "",
        contract_address: contractAddress,
        error: err.message,
      });
    }
  }

  // ── Summary stats ─────────────────────────────────────────────────────
  const successful = results.filter(r => r.verified);
  const gasValues  = successful.map(r => parseInt(r.gas_used));
  const avgGas     = gasValues.length
    ? Math.round(gasValues.reduce((a, b) => a + b, 0) / gasValues.length)
    : 0;
  const avgTime    = successful.length
    ? Math.round(successful.reduce((a, b) => a + b.tx_time_ms, 0) / successful.length)
    : 0;
  const minGas     = gasValues.length ? Math.min(...gasValues) : 0;
  const maxGas     = gasValues.length ? Math.max(...gasValues) : 0;

  console.log("\n" + "=".repeat(65));
  console.log("  BLOCKCHAIN RESULTS (for paper Table 1)");
  console.log("=".repeat(65));
  console.log(`  Contract address  : ${contractAddress}`);
  console.log(`  Deploy time       : ${deployTime} ms`);
  console.log(`  Proofs anchored   : ${successful.length}/${results.length}`);
  console.log(`  Avg gas per proof : ${avgGas} gas units`);
  console.log(`  Min / Max gas     : ${minGas} / ${maxGas}`);
  console.log(`  Avg tx time       : ${avgTime} ms`);
  console.log(`  Gas cost formula  : Tcost = gasLimit × gasPrice`);
  console.log("=".repeat(65));

  // ── Save results ──────────────────────────────────────────────────────
  const outputPath = path.join(__dirname, "../blockchain_results.json");
  fs.writeFileSync(outputPath, JSON.stringify({
    contract_address: contractAddress,
    deploy_time_ms: deployTime,
    network: "localhost (Ganache) — re-run with --network sepolia for testnet",
    summary: {
      total_runs: results.length,
      successful: successful.length,
      avg_gas_used: avgGas,
      min_gas: minGas,
      max_gas: maxGas,
      avg_tx_time_ms: avgTime,
    },
    runs: results
  }, null, 2));

  console.log(`\n  ✅ Full results saved to: blockchain_results.json`);
  console.log("  → Use these numbers in paper Section 6.2 (Performance)\n");
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
